config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :podcasts, only: :index do
    resources :episodes, only: [:index, :show]
    resources :search_results, only: :index
  end

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "podcasts#index"

  resolve "SearchResult" do |search_result|
    [search_result.podcast, search_result.episode]
  end

  mount GoodJob::Engine => "good_job"
end

app/models/application_model.rb
class ApplicationModel
  include ActiveModel::Model
  include ActiveModel::Attributes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :podcast

  has_one_attached :audio

  has_rich_text :transcript

  scope :most_recent_first, -> { order published_at: :desc }
  scope :websearch_transcript, ->(value) {
    joins(:rich_text_transcript).merge ActionText::RichText.websearch_body(value)
  }
  scope :containing, ->(value) {
    if value.present?
      fulltext_search = websearch_transcript(value).select(:id)

      where <<~SQL, query: "%" + sanitize_sql_like(value) + "%"
        title ILIKE :query OR subtitle ILIKE :query OR id IN (#{fulltext_search.to_sql})
      SQL
    end
  }
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  has_many :episodes, dependent: :destroy

  has_one_attached :image
end

app/models/podcast_import.rb
module PodcastImport
  def self.call(url)
    feed = Extract.new(url).call
    podcast, episodes = Transform.new(feed).call
    Load.new(podcast, episodes).call
  end
end

app/models/podcast_import/extract.rb
module PodcastImport
  Extract = Struct.new(:url) do
    def call
      uri = URI(url)
      rss = Net::HTTP.get(uri)

      RSS::Parser.parse(rss)
    end
  end
end

app/models/podcast_import/imported_episode.rb
module PodcastImport
  class ImportedEpisode < DelegateClass(Episode)
    attr_accessor :enclosure

    def initialize(enclosure:, **attributes)
      @record = Episode.new(attributes)
      @enclosure = enclosure
      super(@record)
    end
  end
end

app/models/podcast_import/imported_podcast.rb
module PodcastImport
  class ImportedPodcast < DelegateClass(Podcast)
    attr_accessor :itunes_image

    def initialize(itunes_image:, **attributes)
      @record = Podcast.new(attributes)
      @itunes_image = itunes_image
      super(@record)
    end
  end
end

app/models/podcast_import/load.rb
module PodcastImport
  Load = Struct.new(:podcast, :episodes) do
    def call
      Podcast.transaction do
        Podcast.destroy_by(podcast.slice(:title, :author, :episode_type))

        podcast.update!(episodes: episodes.map(&:to_model))

        DownloadAttachmentJob.perform_later(podcast.to_model, :image, podcast.itunes_image.href)

        episodes.each do |episode|
          DownloadAttachmentJob.perform_later(episode.to_model, :audio, episode.enclosure.url)
        end
      end

      [podcast, episodes]
    end
  end
end

app/models/podcast_import/transform.rb
module PodcastImport
  Transform = Struct.new(:feed) do
    def call
      podcast = ImportedPodcast.new(
        author: feed.channel.itunes_author,
        copyright: feed.channel.copyright,
        description: feed.channel.description,
        episode_type: feed.channel.itunes_type || "episodic",
        explicit: boolean_from(feed.channel.itunes_explicit),
        keywords: feed.channel.itunes_keywords,
        itunes_image: feed.channel.itunes_image,
        language: feed.channel.language,
        published_at: feed.channel.pubDate,
        subtitle: feed.channel.itunes_subtitle,
        title: feed.channel.title
      )

      episodes = feed.items.map do |item|
        ImportedEpisode.new(
          duration: interval_from(item.itunes_duration),
          episode_type: item.itunes_episode || "full",
          enclosure: item.enclosure,
          explicit: boolean_from(item.itunes_explicit),
          guid: item.guid.content,
          published_at: item.pubDate,
          season: item.itunes_season,
          subtitle: item.itunes_subtitle,
          title: item.title,
          transcript: item.content_encoded
        )
      end

      [podcast, episodes]
    end

    private

    def boolean_from(string)
      /yes/i.match?(string)
    end

    def interval_from(duration)
      hours = duration.hour.hours
      minutes = duration.minute.minutes
      seconds = duration.second.seconds

      hours + minutes + seconds
    end
  end
end

app/models/search.rb
class Search < ApplicationModel
  include Pagy::Backend

  attribute :podcast
  attribute :page
  attribute :query, :string

  def search_results
    page, paginated_episodes = pagy episodes

    [page, paginated_episodes.map { SearchResult.new(episode: _1, search: self) }]
  end

  def episodes
    if query.present?
      podcast.episodes.most_recent_first.containing(query)
    else
      podcast.episodes.none
    end
  end

  private

  def params = {page:}
end

app/models/search_result.rb
class SearchResult < ApplicationModel
  attribute :episode
  attribute :search

  delegate :query, to: :search
  delegate_missing_to :episode
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable,
    :confirmable, :lockable, :timeoutable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/podcast_scoped.rb
module PodcastScoped
  extend ActiveSupport::Concern

  included do
    before_action :scope_by_podcast
  end

  def scope_by_podcast
    if (podcast_id = params[:podcast_id])
      set_podcast(podcast_id)
    end
  end

  def set_podcast(podcast_id)
    @podcast = Podcast.find(podcast_id)
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  include PodcastScoped

  def index
    @page, @episodes = pagy @podcast.episodes.most_recent_first
  end

  def show
    @episode = @podcast.episodes.find(params[:id])
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  def index
    @podcasts = Podcast.all

    redirect_to podcast_episodes_url(@podcasts.first)
  end
end

app/controllers/search_results_controller.rb
class SearchResultsController < ApplicationController
  include PodcastScoped

  def index
    @search = Search.new(search_params.merge(podcast: @podcast))
    @page, @search_results = @search.search_results
  end

  private

  def search_params
    params.permit!.slice(:page, :query)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/episodes/_episode.html.erb
<article aria-labelledby="<%= dom_id(episode, :title) %>" class="py-10 sm:py-12">
  <div class="lg:px-8">
    <div class="lg:max-w-4xl">
      <div class="mx-auto px-4 sm:px-6 md:max-w-2xl md:px-4 lg:px-0">
        <div class="flex flex-col items-start">
          <h2 id="<%= dom_id(episode, :title) %>" class="mt-2 text-lg font-bold text-slate-900">
            <%= link_to episode.title, podcast_episode_path(episode.podcast, episode) %>
          </h2>

          <%= time_tag episode.published_at.to_date, class: "order-first font-mono text-sm leading-7 text-slate-500" %>

          <p class="mt-1 text-base leading-7 text-slate-700"><%= episode.subtitle %></p>

          <div class="mt-4 flex items-center gap-4">
            <%= tag.form(
              action: podcast_episode_path(episode.podcast, episode),
              data: {
                action: "submit->application#preventDefault:reload",
                turbo_frame: "audio"
              }
            ) do %>
              <button class="group flex items-center text-sm font-bold leading-6 text-pink-500 hover:text-pink-700 active:text-pink-900"
                      data-controller="play-button"
                      data-play-button-player-outlet="#<%= dom_id(episode, :audio) %>"
                      data-action="click->play-button#toggle">
                <% with_options class: "h-2.5 w-2.5 fill-current" do |styled| %>
                  <div class="block group-aria-pressed:hidden">
                    <span class="sr-only">Play episode <%= episode.title %></span>
                    <%= styled.inline_svg_tag "icons/play.svg" %>
                  </div>

                  <div class="hidden group-aria-pressed:block">
                    <span class="sr-only">Pause episode <%= episode.title %></span>
                    <%= styled.inline_svg_tag "icons/pause.svg" %>
                  </div>
                <% end %>

                <span class="ml-3" aria-hidden="true">Listen</span>
              </button>
            <% end %>

            <span aria-hidden="true" class="text-sm font-bold text-slate-400">/</span>

            <%= link_to "Show notes", podcast_episode_path(episode.podcast, episode), class: "flex items-center text-sm font-bold leading-6 text-pink-500 hover:text-pink-700 active:text-pink-900", aria: {label: "Show notes for episode #{episode.title}"} %>
          </div>
        </div>
      </div>
    </div>
  </div>
</article>

app/views/episodes/_play_button.html.erb
<%
  sizes = %i[small large]
  variant = local_assigns[:variant].presence_in(sizes) || sizes.first
  size = variant.to_s.inquiry
%>

<%= link_to url_for(autoplay: autoplay ? nil : true), class: class_names("group relative flex flex-shrink-0 items-center justify-center rounded-full bg-slate-700 hover:bg-slate-900 focus:outline-none focus:ring-slate-700 focus:ring focus:ring-offset-4", "h-18 w-18" => size.large?, "h-14 w-14" => size.small?), aria: {label: autoplay ? "Pause" : "Play"} do %>
  <div class="absolute -inset-3 md:hidden"></div>
  <%= inline_svg_tag autoplay ? "icons/pause.svg" : "icons/play.svg", class: class_names("fill-white group-active:fill-white/80", "h-7 w-7" => size.large?, "h-5 w-5" => size.small?) %>
<% end %>

app/views/episodes/_player.html.erb
<div id="player" class="fixed inset-x-0 bottom-0 z-10 lg:left-112 xl:left-120" data-turbo-permanent>
  <%= tag.turbo_frame yield.presence, id: "audio", class: "flex items-center gap-6 bg-white/90 py-4 px-4 shadow shadow-slate-200/80 ring-1 ring-slate-900/5 backdrop-blur-sm empty:hidden md:px-6", target: "_top" %>
</div>

app/views/episodes/index.html.erb
<%= render "episodes/podcast/frame", podcast: @podcast do %>
  <div class="pt-16 pb-12 sm:pb-4 lg:pt-12">
    <div class="lg:px-8">
      <div class="lg:max-w-4xl">
        <div class="mx-auto px-4 sm:px-6 md:max-w-2xl md:px-4 lg:px-0">
          <h1 id="main_title" class="text-2xl font-bold leading-7 text-slate-900">Episodes</h1>
        </div>
      </div>
    </div>

    <div class="divide-y divide-slate-100 sm:mt-4 lg:mt-8 lg:border-t lg:border-slate-100">
      <turbo-frame id="page_<%= @page.page %>" target="_top">
        <% if @page.prev %>
          <div class="py-10 sm:py-12 hidden first:block">
            <div class="lg:px-8">
              <div class="lg:max-w-4xl">
                <div class="flex justify-center mx-auto px-4 sm:px-6 md:max-w-2xl md:px-4 lg:px-0">
                  <%= link_to pagy_url_for(@page, @page.prev), rel: "prev",
                    class: "flex animate-bounce items-center justify-center rounded-full bg-white p-2 shadow-lg text-pink-500 ring-1 ring-slate-900/5 focus:ring hover:text-pink-700 active:text-pink-900" do %>
                    <span class="sr-only">Load newer episodes</span>
                    <%= inline_svg_tag "icons/up_arrow.svg", class: "h-6 w-6" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>

        <%= render @episodes %>

        <% if @page.next %>
          <%= tag.turbo_frame id: "page_#{@page.next}", src: pagy_url_for(@page, @page.next), loading: "lazy",
                data: {turbo_action: "replace", controller: "element", action: "turbo:frame-load->element#replaceWithChildren"} do %>
            <div class="py-10 sm:py-12 hidden last:block">
              <div class="lg:px-8">
                <div class="lg:max-w-4xl">
                  <div class="flex justify-center mx-auto px-4 sm:px-6 md:max-w-2xl md:px-4 lg:px-0">
                    <%= link_to pagy_url_for(@page, @page.next), rel: "next",
                      class: "flex animate-bounce items-center justify-center rounded-full bg-white p-2 shadow-lg text-pink-500 ring-1 ring-slate-900/5 focus:ring hover:text-pink-700 active:text-pink-900" do %>
                      <span class="sr-only">Load older episodes</span>
                      <%= inline_svg_tag "icons/down_arrow.svg", class: "h-6 w-6" %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </turbo-frame>
    </div>
  </div>
<% end %>

app/views/episodes/podcast/_frame.html.erb
<header class="bg-slate-50 lg:fixed lg:inset-y-0 lg:left-0 lg:flex lg:w-112 lg:items-start lg:overflow-y-auto xl:w-120"><div class="hidden lg:sticky lg:top-0 lg:flex lg:w-16 lg:flex-none lg:items-center lg:whitespace-nowrap lg:py-12 lg:text-sm lg:leading-7 lg:[writing-mode:vertical-rl]">
    <span class="font-mono text-slate-500">Hosted by</span><span class="mt-6 flex gap-6 font-bold text-slate-900"><%= podcast.author %></span>
  </div>
  <div class="relative z-10 mx-auto px-4 pb-4 pt-10 sm:px-6 md:max-w-2xl md:px-4 lg:min-h-full lg:flex-auto lg:border-x lg:border-slate-200 lg:py-12 lg:px-8 xl:px-12">
    <%= link_to podcast_episodes_path(podcast), class: "relative mx-auto block w-48 overflow-hidden rounded-lg bg-slate-200 shadow-xl shadow-slate-200 sm:w-64 sm:rounded-xl lg:w-auto lg:rounded-2xl", aria: {label: podcast.title} do %>
      <%= image_tag podcast.image.representation(resize_to_fit: [960, 960]), class: "w-full", width: 960, height: 960, decoding: "async" %>
      <div class="absolute inset-0 rounded-lg ring-1 ring-inset ring-black/10 sm:rounded-xl lg:rounded-2xl"></div>
    <% end %>

    <div class="mt-10 text-center lg:mt-12 lg:text-left">
      <p class="text-xl font-bold text-slate-900">
        <%= link_to podcast.title, podcast_episodes_path(podcast) %>
      </p>
      <p class="mt-3 text-lg font-medium leading-8 text-slate-700"><%= podcast.subtitle %></p>
    </div>

    <section class="mt-10 lg:mt-12">
      <div class="border border-gray-300 bg-white rounded-md shadow-sm text-slate-500 focus-within:ring">
        <%= link_to podcast_search_results_path(podcast), class: "outline-none",
              aria: {keyshortcuts: "Meta+k"},
              data: {hotkey_target: "shortcut"} do %>
          <div class="flex items-center gap-5 px-3 text-start">
            <%= inline_svg_tag "icons/search.svg", class: "h-2.5 w-2.5" %>

            <div class="flex-1 py-1">
              <span class="font-mono text-sm leading-7">Search</span>
            </div>

            <kbd class="inline-flex items-center gap-1 font-mono text-sm leading-7">
              <abbr title="Command" class="no-underline text-slate-300">⌘</abbr> K
            </kbd>
          </div>
        <% end %>
      </div>
    </section>

    <section class="mt-12 hidden lg:block">
      <h2 class="flex items-center font-mono text-sm font-medium leading-7 text-slate-900">
        <%= inline_svg_tag "icons/graph.svg", class: "h-2.5 w-2.5" %>
        <span class="ml-2.5">About</span>
      </h2>

      <p class="mt-2 text-base leading-7 text-slate-700 lg:line-clamp-4"><%= podcast.description %></p>
    </section>
  </div>
</header>

<main class="border-t border-slate-200 lg:relative lg:mb-28 lg:ml-112 lg:border-t-0 xl:ml-120" aria-labelledby="main_title">
  <%= inline_svg_tag "waveform.svg", class: "absolute left-0 top-0 h-20 w-full" %>

  <div class="relative">
    <%= yield %>
  </div>

  <%= render "episodes/player" do %>
    <% if partial.player %>
      <%= partial.yield :player %>
    <% end %>
  <% end %>
</main>

<footer class="border-t border-slate-200 bg-slate-50 py-10 pb-40 sm:py-16 sm:pb-32 lg:hidden">
  <div class="mx-auto px-4 sm:px-6 md:max-w-2xl md:px-4">
    <section>
      <h2 class="flex items-center font-mono text-sm font-medium leading-7 text-slate-900">
        <%= inline_svg_tag "icons/graph.svg", class: "text-violet-300 h-2.5 w-2.5" %>
        <span class="ml-2.5">About</span>
      </h2>

      <p class="mt-2 text-base leading-7 text-slate-700 lg:line-clamp-4"><%= podcast.description %></p>

      <button type="button" class="mt-2 hidden text-sm font-bold leading-6 text-pink-500 hover:text-pink-700 active:text-pink-900 lg:inline-block">Show more</button>
    </section>

    <h2 class="mt-8 flex items-center font-mono text-sm font-medium leading-7 text-slate-900">
      <%= inline_svg_tag "icons/person.svg", class: "h-3 w-auto fill-slate-300" %>
      <span class="ml-2.5">Hosted by</span>
    </h2>

    <div class="mt-2 flex gap-6 text-sm font-bold leading-7 text-slate-900">
      <%= podcast.author %>
    </div>
  </div>
</footer>

app/views/episodes/show.html.erb
<%= render "episodes/podcast/frame", podcast: @episode.podcast do |frame| %>
  <article class="py-16 lg:py-36">
    <div class="lg:px-8">
      <div class="lg:max-w-4xl">
        <div class="mx-auto px-4 sm:px-6 md:max-w-2xl md:px-4 lg:px-0">
          <header class="flex flex-col">
            <div class="flex items-center gap-6">
              <form class="relative flex-shrink-0"
                    data-action="submit->application#preventDefault:reload"
                    data-turbo-frame="audio">
                <button class="group flex items-center justify-center rounded-full bg-slate-700 h-18 w-18 hover:bg-slate-900 focus:outline-none focus:ring-slate-700 focus:ring focus:ring-offset-4"
                        data-controller="play-button"
                        data-play-button-player-outlet="#<%= dom_id(@episode, :audio) %>"
                        data-action="click->play-button#toggle">
                  <div class="absolute -inset-3 md:hidden"></div>

                  <% with_options class: "h-7 w-7 fill-white group-active:fill-white/80" do |styled| %>
                    <div class="block group-aria-pressed:hidden">
                      <span class="sr-only">Play</span>
                      <%= styled.inline_svg_tag "icons/play.svg" %>
                    </div>

                    <div class="hidden group-aria-pressed:block">
                      <span class="sr-only">Pause</span>
                      <%= styled.inline_svg_tag "icons/pause.svg" %>
                    </div>
                  <% end %>
                </button>
              </form>

              <div class="flex flex-col">
                <h1 id="main_title" class="mt-2 text-4xl font-bold text-slate-900">
                  <%= @episode.title %>
                </h1>

                <%= time_tag @episode.published_at.to_date, class: "order-first font-mono text-sm leading-7 text-slate-500" %>
              </div>
            </div>

            <p class="ml-24 mt-3 text-lg font-medium leading-8 text-slate-700">
              <%= @episode.subtitle %>
            </p>
          </header>

          <hr class="my-12 border-gray-200">

          <%= @episode.transcript %>
        </div>
      </div>
    </div>
  </article>

  <% frame.player do %>
    <div class="mb-[env(safe-area-inset-bottom)] flex flex-1 flex-col gap-3 overflow-hidden p-1">
      <%= link_to @episode.title, podcast_episode_path(@episode.podcast, @episode), class: "truncate text-center text-sm font-bold leading-6 md:text-left" %>

      <%= audio_tag @episode.audio, id: dom_id(@episode, :audio), class: "w-full", controls: true, muted: Rails.env.test?,
            data: {controller: "player", action: "loadeddata->player#play"} %>
    </div>
  <% end %>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="prose prose-slate mt-14
            [&>h2]:mt-12
            [&>h2]:flex
            [&>h2]:items-center
            [&>h2]:font-mono
            [&>h2]:text-sm
            [&>h2]:font-medium
            [&>h2]:leading-7
            [&>h2]:text-slate-900
            [&>h2]:before:mr-3
            [&>h2]:before:h-3
            [&>h2]:before:w-1.5
            [&>h2]:before:rounded-r-full
            [&>h2]:before:bg-cyan-200
            [&>ul]:mt-6
            [&>ul]:list-['\2013\20']
            [&>ul]:pl-5
            [&>h2:nth-of-type(3n+2)]:before:bg-indigo-200
            [&>h2:nth-of-type(3n)]:before:bg-violet-200">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-controller="application">
  <head>
    <title>Botcasts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_tag type: "module", nonce: true do %>
      import debounced from "debounced"

      debounced.initialize(<%= raw Rails.configuration.debounced.to_json %>)
    <% end %>
  </head>

  <body data-controller="hotkey">
    <%= yield %>
  </body>
</html>

app/views/search_results/_search_result.html+turbo_frame.erb
<%= button_to podcast_episode_path(search_result.podcast, search_result.episode), method: "get",
      id: dom_id(search_result), tabindex: "-1", role: "option",
      class: "w-full hover:bg-slate-100 aria-selected:bg-slate-100",
      aria: {labelledby: dom_id(search_result, :title)},
      data: {turbo_frame: "_top"} do %>
  <div class="flex flex-col items-start gap-1 select-none text-start px-4 py-2">
    <span id="<%= dom_id(search_result, :title) %>" class="font-medium">
      <%= highlight search_result.title, search_result.query %>
    </span>

    <p>
      <%= highlight(
        excerpt(search_result.transcript.to_plain_text, search_result.query, radius: 35),
        search_result.query
      ) %>
    </p>
  </div>
<% end %>

app/views/search_results/_search_result.html.erb
<article aria-labelledby="<%= dom_id(search_result, :title) %>" class="py-10 sm:py-12">
  <div class="lg:px-8">
    <div class="lg:max-w-4xl">
      <div class="mx-auto px-4 sm:px-6 md:max-w-2xl md:px-4 lg:px-0">
        <div class="flex flex-col items-start">
          <h2 id="<%= dom_id(search_result, :title) %>" class="mt-2 text-lg font-bold text-slate-900">
            <%= link_to search_result do %>
              <%= highlight search_result.title, search_result.query %>
            <% end %>
          </h2>

          <%= time_tag search_result.published_at.to_date, class: "order-first font-mono text-sm leading-7 text-slate-500" %>

          <p class="mt-1 text-base leading-7 text-slate-700">
            <%= highlight(
              excerpt(search_result.subtitle, search_result.query),
              search_result.query
            ) %>
          </p>

          <p class="mt-1 text-base leading-7 text-slate-700">
            <%= highlight(
              excerpt(search_result.transcript.to_plain_text, search_result.query),
              search_result.query
            ) %>
          </p>

          <div class="mt-4 flex items-center gap-4">
            <form action="<%= url_for(search_result) %>"
                  data-action="submit->application#preventDefault:reload"
                  data-turbo-frame="audio">
              <button class="group flex items-center text-sm font-bold leading-6 text-pink-500 hover:text-pink-700 active:text-pink-900"
                      data-controller="play-button"
                      data-play-button-player-outlet="#<%= dom_id(search_result.episode, :audio) %>"
                      data-action="click->play-button#toggle">
                <% with_options class: "h-2.5 w-2.5 fill-current" do |styled| %>
                  <div class="block group-aria-pressed:hidden">
                    <span class="sr-only">Play episode <%= search_result.title %></span>
                    <%= styled.inline_svg_tag "icons/play.svg" %>
                  </div>

                  <div class="hidden group-aria-pressed:block">
                    <span class="sr-only">Pause episode <%= search_result.title %></span>
                    <%= styled.inline_svg_tag "icons/pause.svg" %>
                  </div>
                <% end %>

                <span class="ml-3" aria-hidden="true">Listen</span>
              </button>
            </form>

            <span aria-hidden="true" class="text-sm font-bold text-slate-400">/</span>

            <%= link_to "Show notes", search_result, class: "flex items-center text-sm font-bold leading-6 text-pink-500 hover:text-pink-700 active:text-pink-900", aria: {label: "Show notes for episode #{search_result.title}"} %>
          </div>
        </div>
      </div>
    </div>
  </div>
</article>

app/views/search_results/options/_search_result.html.erb
<%= button_to podcast_episode_path(search_result.podcast, search_result.episode), method: "get",
      id: dom_id(search_result), tabindex: "-1", role: "option",
      class: "w-full hover:bg-slate-100 aria-selected:bg-slate-100",
      aria: {labelledby: dom_id(search_result, :title)},
      data: {turbo_frame: "_top"} do %>
  <div class="flex flex-col items-start gap-1 select-none text-start px-4 py-2">
    <span id="<%= dom_id(search_result, :title) %>" class="font-medium">
      <%= highlight search_result.title, search_result.query %>
    </span>

    <p>
      <%= highlight(
        excerpt(search_result.transcript.to_plain_text, search_result.query, radius: 35),
        search_result.query
      ) %>
    </p>
  </div>
<% end %>

app/views/searches/search/_empty.html.erb
<div class="py-10 sm:py-12">
  <div class="lg:px-8">
    <div class="lg:max-w-4xl">
      <div class="mx-auto px-4 sm:px-6 md:max-w-2xl md:px-4 lg:px-0">
        <p class="font-mono text-sm font-medium leading-7 text-slate-900">
          We couldn't find any episodes matching "<%= search.query %>".
        </p>
      </div>
    </div>
  </div>
</div>